# Data Retrieval Notebook for Table: Customer

In [1]:
# Import required library packages
import base64
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
# Connection details
connection_string = b'<<generated-base64-string>>'

In [3]:
# Establish the connection
engine = create_engine(base64.b64decode(connection_string).decode("ascii"))

In [4]:
# Format SQL Query
def format_sql_query(query):
    formatted_query = sqlparse.format(query, reindent=True, keyword_case="upper")
    return formatted_query.strip()

In [5]:
# Execute Select Query
def exec_sql_query(sql=None, con=engine, params=None):
    df = pd.read_sql_query(sql=text(query), con=engine, params=params)
    df_filtered = df.dropna(axis=1, how='all')
    return (df, df_filtered)

In [6]:
# Parameter variables for Customer
SupportRepId = '3'
CustomerId = '1'

```sql
SELECT *
FROM Customer
LIMIT 10;
```

In [7]:
# Query for Customer
query = \
"""
SELECT *
FROM Customer
LIMIT 10;
"""

In [8]:
# Parameters for Customer
parameters = {}

In [9]:
# Execute sql query and display
df, df_filtered = exec_sql_query(sql=text(query), con=engine, params=parameters)

In [10]:
# Display information
df_filtered.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

```sql
SELECT *
FROM Customer
WHERE SupportRepId = :SupportRepId;
```

In [11]:
# Query for Customer
query = \
"""
SELECT *
FROM Customer
WHERE SupportRepId = :SupportRepId;
"""

In [12]:
# Parameters for Customer
parameters = {"SupportRepId": SupportRepId}

In [13]:
# Execute sql query and display
df, df_filtered = exec_sql_query(sql=text(query), con=engine, params=parameters)

In [14]:
# Display information
df_filtered.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
2,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
3,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
4,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3

```sql
SELECT *
FROM Customer
WHERE CustomerId = :CustomerId;
```

In [15]:
# Query for Customer
query = \
"""
SELECT *
FROM Customer
WHERE CustomerId = :CustomerId;
"""

In [16]:
# Parameters for Customer
parameters = {"CustomerId": CustomerId}

In [17]:
# Execute sql query and display
df, df_filtered = exec_sql_query(sql=text(query), con=engine, params=parameters)

In [18]:
# Display information
df_filtered.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3

In [19]:
# Disconnect
engine.dispose()